### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by reidrac** [reidrac/z80count#18]
Version 0.8.0 is not Python 2 compatible:
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from z80count.z80count import version
  File "/home/user/src/z80count/z80count/z80count.py", line 43
    print(message % args, file=sys.stderr)
```

Python 2 support is optional, but seems silly to break compatibility just because of that (initially, I haven't checked further).

**Comment by reidrac** [comment]
That ship has sailed, using `cnofigparser` too. A bit of a shame.
